### ISSUE TITLE
CORS error on browser request

### ISSUE THREAD

**Issue by Chieftl** [captn3m0/jqaas#1]
I'm trying to make request to jqass from browser, but this error is generated anytime:
**Access to XMLHttpRequest at 'https://jqaas.captnemo.in/?url=https://thisdavej.api.stdlib.com/weather/current/?loc=Ivano-Frankivsk%26deg=C' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

Please update response headers to allow CORS
https://enable-cors.org/server_php.html

**Comment by captn3m0** [comment]
I was never expecting that someone was using this project. This was a quick fix, so I've made the change.

Just curious, what are you using it for, and how did you find it?

**Comment by captn3m0** [comment]
Tagging @Chieftl in case you missed this
