### ISSUE TITLE
Service down on `jqaas.captnemo.in`

### ISSUE THREAD

**Issue by PeterDaveHello** [captn3m0/jqaas#2]
503 Server Error on https://jqaas.captnemo.in/ now 😅 

![image](https://user-images.githubusercontent.com/3691490/204851595-f7759bb7-f983-47f4-9ffc-42ae2708069f.png)

**Comment by captn3m0** [comment]
Was hosted on Heroku, and recent changes have meant I can't even upgrade it to keep it running: https://github.com/heroku/roadmap/issues/17

So unlikely to come back anytime soon unless I host it elsewhere. We're you using it for anything?

**Comment by PeterDaveHello** [comment]
Fair enough. Maybe you'd like to try something like https://fly.io/, https://www.netlify.com/ or https://render.com/ ? Would be great if there's an "official" site for testing anything 😍

**Comment by PeterDaveHello** [comment]
This may be useful 😃 

https://github.com/Engagespot/heroku-free-alternatives

**Comment by captn3m0** [comment]
http://jqplay.org/ is a good alternative in the interim. I'll see if I can migrate this somewhere - this would work nicely as a cloudflare worker perhaps.

But no guarantees or timelines.

**Comment by captn3m0** [comment]
I've been trying fly.io elsewhere, so deployed this to render.com for a change. URL remains the same, I just upgraded to php8.1 alongside.

**Comment by PeterDaveHello** [comment]
That's awesome @captn3m0 😍 Thank you!

**Comment by PeterDaveHello** [comment]
Looks like the URL feature is broken though 😱

`https://jqaas.captnemo.in/?url=https://jsonblob.com/api/1048224244483506176` or any other URLs returned 400 client-side error 😭

**Comment by captn3m0** [comment]
Just pushed a change to fix this. I'd forgotten to install openssl, so it was working with HTTP URLs, but not HTTPS. Works now:

```
curl -H "JQ-Filter: .hello" https://jqaas.captnemo.in/?url=https://jsonblob.com/api/1048224244483506176 -i
HTTP/2 200
date: Thu, 15 Dec 2022 13:02:02 GMT
content-type: application/json
cf-ray: 779f5f014cf63971-MAA
access-control-allow-origin: *
vary: Accept-Encoding
cf-cache-status: DYNAMIC
x-powered-by: PHP/8.1.13
server: cloudflare
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

[1,2,3]
```
